### ISSUE TITLE
[Fonction manquante] cadeau suggéré

### ISSUE THREAD

**Issue by zeugmaMTP** [acemtp/webdo#1]
Ya plus et en plus je crois que je vois ceux qui sont dans ma liste actuelle (pas cool)

**Comment by peernohell** [comment]
hum. je vais verifier. normalement j'ai garder le fait de pas voir les cadeau suggerer par contre j'avais garder l'information pour ne pas les afficher.
Merci en tous cas

**Comment by peernohell** [comment]
c'est corriger.
Désolé pour tes cadeau suggérer. il me semblait l'avoir implémenter mais il manquait un bout.
