### ISSUE TITLE
[fonctionnalité manquante] Désarchiver et copier

### ISSUE THREAD

**Issue by zeugmaMTP** [acemtp/webdo#2]
Plus possible de de remettre un cadeau dans la liste depuis la page cadeau (uniquement dans le liste)
Plus de "je veux le même" ou "j'en reveux"

**Comment by peernohell** [comment]
Tu veux dire quoi par remettre un cadeau dans la liste?

**Comment by zeugmaMTP** [comment]
J'ai archivé mon cadeau (par erreur) ou quelqu'un l'a fait pour moi alors que je ne voulais pas et je veux le remettre dans ma liste "normale".
Ou j'ai pas vu comment faire (oups)

**Comment by peernohell** [comment]
Tous en bas de la liste des cadeau il y  a un liens qui permet de revoir les cadeaux archiver. Il es pas tres visible. il faut que j'ameliore ca.
une fois que tu vois ton cadeau tu peu cliquer sur l'icone pour le desarchiver

**Comment by zeugmaMTP** [comment]
Bon alors ça marche pas :smiling_imp: 
Je suis sur la fiche de mon cadeau archivé : il me propose d'archiver (et pas de désachiver) et ça fait rien
Je suis sur la liste des cadeaux archivés : je clique sur l'icone (bas droite) le cadeau diparait de la liste. Je vais sur ma liste de cadeaux (normaux) il n'y est pas, je retourne dans les cadeaux archivés, il y est à nouveau.
