### ISSUE TITLE
[Navigation] atterrisage sur page non instinctive

### ISSUE THREAD

**Issue by zeugmaMTP** [acemtp/webdo#4]
Après validation d'un nouveau cadeau, j'aimerai voir ce cadeau (pas la liste de personne ou de mes cadeaux)
Après de-sarchivage d'un cadeau, j'aimerai "suivre" le cadeau et me retrouver sur la liste des cadeaux archiver

**Comment by peernohell** [comment]
Ok lors de la creation d'un cadeau
par contre pour ce qui est de desarchiver un cadeau je suis pas sur de bien comprendre. Il faudra que tu m'explique exactement :)

**Comment by peernohell** [comment]
j'ai fait la redirection lors de la creation ou mis a jour d'un cadeau
