### ISSUE TITLE
[Divers] petits machins

### ISSUE THREAD

**Issue by zeugmaMTP** [acemtp/webdo#5]
- encode des titres : accents dans titre ancients cadeaux mal encodés/decodés
- Quelle différence entre "Commentaire" et "Ce message sera visible par" ?
  Possibilité de faire un commentaire non visible (genre "je lui prend une carte à trouze brouzouf")
-  information : pas d'infobulle ni de légende sur les icones d'actions dans la liste (on ne sait pas ce que ça va faire si on clique)
  ! on ne devrait pouvoir acheter le cadeau dans la liste qui si c'est nous qui l'avons reservé ! pour éviter les maladresses (genre "je pensais avec réservé") + confirmation si on force l'achat d'un cadeau pas reservé par nous
- confirmation pour l'archivage (pour éviter les clics à coté)
- orthographe : "cadeaux archivés" au lieu de "cadeaux archiver" en bas de liste
- information : on ne sais pas qui a réservé le cadeaux au niveau de la liste.

**Comment by peernohell** [comment]
- pour les titres. le problème est la methode que j'ai trouver ne semble pas fonctionner tous le temps. Je sais pas pourquoi. Certain titre on bien leurs accent et d'autre pas :/
- Commentaire => visible par tous le monde sauf le possesseur du cadeau. "ce message sera visible par" => sont les message visible par tous le monde.
- je rajouterais des info bulle. Le but c'est que les icônes soit compréhensible sans texte. Il faudrait peut être que j'en utilise d'autre. 
- Oui bonne idée de forcé la confirmation si quelqu'un souhaite acheter un cadeau réserver par quelqu'un d'autre.
- plutôt qu'une confirmation je préfère le faire comme dans gmail et mettre un petit message qui propose d'annulé 
- ok pour la correction. J'en profite pour te montré une super feature de github. tu peut directement l'éditer depuis le site. Quand tu es sur le fichier https://github.com/acemtp/meteor-webdo/blob/master/webdo.jade tu as une petite icône de craillons à coté de "blame", "raw", "history". Tu clique dessus puis tu va directement ligne 81 tu modifie le texte. puis tous en bas tu met un message de commit et tu clique sur le bouton "commits changes" il va surement te proposé ou te dire qu'il a forké le projet. c'est normal.

Dernier info. Ici c'est l'ancien webdo en php. voici l'url du projet meteor
https://github.com/acemtp/meteor-webdo

**Comment by zeugmaMTP** [comment]
Super le truc qui permet d'annuler :+1: (à la place de la confirmation)
InfoBulle + Commentaires : faut pas oublier qu'il y a des pas doués en site (ma belle famille par ex.) donc pour moi, faut des explications.
Merci pour les infos+ , j'essaie de rien casser :tongue:

**Comment by zeugmaMTP** [comment]
Un autre truc partique : rappeler quelque part à qui est la liste qu'on visualise (avec un résumé du profile ?)

**Comment by peernohell** [comment]
pour le a qui est la liste. je vais du coup l'ajouter avec les infos (preference et a evitier) une fois que je 'aurais ajouter au profile de l'utilisateur.
